# Sample config for Prometheus.

global:
  scrape_interval:    60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout:      55s # scrape_timeout is set to the global default (10s).

  external_labels:
      monitor: 'speedtest-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

scrape_configs:
  - job_name: 'rocky_vm_prometheus'
    static_configs:
      - targets: ['192.168.56.56:9090']
      
  - job_name: 'rocky_vm_node'
    static_configs:
      - targets: ['192.168.56.56:9100']

  - job_name: 'rocky_vm_ib'
    static_configs:
      - targets: ['192.168.56.56:9999']
      
  - job_name: 'rocky_vm_speedtest'
    static_configs:
      - targets: ['192.168.56.56:9798']
